import type {
  Brand,
  AppUser,
  Campaign,
  PriorityTask,
  AIAction,
  StrategyPillar,
  BudgetAllocation,
  ContentAsset,
  SalesAsset,
  PerformanceMetric,
  ApprovalRequest,
  ComplianceItem,
  KPI,
} from './types'

export const BRANDS: Brand[] = [
  {
    id: 'group',
    name: 'RGF Staffing Belgium',
    shortName: 'Group',
    color: '#1e293b',
    accentColor: '#7c3aed',
    bgColor: '#f5f3ff',
    description: 'Group-level overview across all brands',
  },
  {
    id: 'start-people',
    name: 'Start People',
    shortName: 'Start People',
    color: '#0ea5e9',
    accentColor: '#0284c7',
    bgColor: '#f0f9ff',
    description: 'Temporary staffing & flex workforce solutions',
  },
  {
    id: 'unique',
    name: 'Unique',
    shortName: 'Unique',
    color: '#f59e0b',
    accentColor: '#d97706',
    bgColor: '#fffbeb',
    description: 'Office & professional staffing',
  },
  {
    id: 'express-medical',
    name: 'Express Medical',
    shortName: 'Exp. Medical',
    color: '#10b981',
    accentColor: '#059669',
    bgColor: '#f0fdf4',
    description: 'Healthcare & medical staffing',
  },
  {
    id: 'solvus',
    name: 'Solvus',
    shortName: 'Solvus',
    color: '#6366f1',
    accentColor: '#4f46e5',
    bgColor: '#eef2ff',
    description: 'HR services & workforce solutions',
  },
  {
    id: 'bright-plus',
    name: 'Bright Plus',
    shortName: 'Bright Plus',
    color: '#ec4899',
    accentColor: '#db2777',
    bgColor: '#fdf2f8',
    description: 'Executive & specialist recruitment',
  },
  {
    id: 'usg-professionals',
    name: 'USG Professionals',
    shortName: 'USG Pro',
    color: '#f97316',
    accentColor: '#ea580c',
    bgColor: '#fff7ed',
    description: 'IT, engineering & finance professionals',
  },
]

export const USERS: AppUser[] = [
  {
    id: 'u1',
    name: 'Christophe Halart',
    initials: 'CH',
    role: 'group_marketing_director',
    roleLabel: 'Group Marketing Director',
    accessScope: 'group_all_brands',
    primaryBrand: 'group',
    allowedBrands: ['group', 'start-people', 'unique', 'express-medical', 'solvus', 'bright-plus', 'usg-professionals'],
  },
  {
    id: 'u2',
    name: 'Sophie Martens',
    initials: 'SM',
    role: 'brand_marketing_manager',
    roleLabel: 'Brand Marketing Manager',
    accessScope: 'brand_only',
    primaryBrand: 'unique',
    allowedBrands: ['unique'],
  },
  {
    id: 'u3',
    name: 'Thomas Dubois',
    initials: 'TD',
    role: 'campaign_manager',
    roleLabel: 'Campaign Manager',
    accessScope: 'multi_brand',
    primaryBrand: 'start-people',
    allowedBrands: ['start-people', 'solvus'],
  },
]

export const PRIORITY_TASKS: PriorityTask[] = [
  {
    id: 't1',
    title: 'Q2 Campaign Approval — Unique Spring',
    description: 'Quarterly brand campaign awaiting final sign-off from Marketing Director before go-live on May 5.',
    brand: 'unique',
    deadline: '2026-05-03',
    owner: 'Sophie Martens',
    priority: 'critical',
    impact: '€45K budget activation',
    status: 'overdue',
    hub: 'campaigns',
  },
  {
    id: 't2',
    title: 'LinkedIn Employer Brand — Start People',
    description: 'Monthly LinkedIn content pack not yet published. Risk of gap in employer brand presence.',
    brand: 'start-people',
    deadline: '2026-05-01',
    owner: 'Thomas Dubois',
    priority: 'high',
    impact: 'Employer brand continuity',
    status: 'at-risk',
    hub: 'content-sales',
  },
  {
    id: 't3',
    title: 'GDPR Consent Audit — Email Campaigns',
    description: 'Compliance review of email subscriber lists required before next bulk send.',
    brand: 'group',
    deadline: '2026-05-15',
    owner: 'Legal & Compliance',
    priority: 'critical',
    impact: 'Regulatory risk',
    status: 'at-risk',
    hub: 'performance',
  },
  {
    id: 't4',
    title: 'Budget Reallocation — Express Medical Q2',
    description: 'Underspend in print (€8K) needs reallocation to digital channels before quarter-end.',
    brand: 'express-medical',
    deadline: '2026-05-10',
    owner: 'Christophe Halart',
    priority: 'high',
    impact: '€8K budget optimization',
    status: 'on-track',
    hub: 'strategy',
  },
  {
    id: 't5',
    title: 'Sales Kit Update — Bright Plus Executive',
    description: 'Q2 sales deck refresh needed to reflect new fee structure and updated case studies.',
    brand: 'bright-plus',
    deadline: '2026-05-08',
    owner: 'Sales Enablement',
    priority: 'medium',
    impact: 'Sales conversion support',
    status: 'on-track',
    hub: 'content-sales',
  },
  {
    id: 't6',
    title: 'YouTube Campaign — USG Professionals',
    description: 'Video production brief needs sign-off to maintain launch timeline for IT candidate campaign.',
    brand: 'usg-professionals',
    deadline: '2026-05-06',
    owner: 'Digital Team',
    priority: 'high',
    impact: 'IT candidate pipeline',
    status: 'at-risk',
    hub: 'campaigns',
  },
]

export const AI_ACTIONS: AIAction[] = [
  {
    id: 'ai1',
    title: 'Boost Unique campaign with LinkedIn retargeting',
    description:
      'CTR on Unique Spring campaign is 18% below benchmark. AI recommends adding LinkedIn retargeting audience (website visitors, 30-day window) to recover reach.',
    type: 'recommendation',
    impact: 'high',
    effort: 'low',
    brand: 'unique',
  },
  {
    id: 'ai2',
    title: 'Candidate shortage alert — healthcare profiles',
    description:
      'Express Medical job applications dropped 31% vs. last month. Recommend activating candidate re-engagement email sequence targeting passive healthcare profiles.',
    type: 'alert',
    impact: 'high',
    effort: 'medium',
    brand: 'express-medical',
  },
  {
    id: 'ai3',
    title: 'Repurpose top-performing Start People content',
    description:
      'Your "Working Flex" Instagram reel has 3.2x average engagement. AI recommends adapting it to Facebook and LinkedIn for organic reach amplification.',
    type: 'opportunity',
    impact: 'medium',
    effort: 'low',
    brand: 'start-people',
  },
  {
    id: 'ai4',
    title: 'Brand consistency risk — Solvus digital assets',
    description:
      'Automated brand scan detected 4 Solvus assets using outdated logo variant (pre-2025 brand refresh). Update required before next campaign activation.',
    type: 'risk',
    impact: 'medium',
    effort: 'low',
    brand: 'solvus',
  },
  {
    id: 'ai5',
    title: 'High-intent week: May 12–16 (Recruitment Fair)',
    description:
      'Brussels Recruitment Fair 2026 is May 14. AI recommends scheduling LinkedIn + email sequences for May 12–13 to capture pre-fair candidate interest.',
    type: 'opportunity',
    impact: 'high',
    effort: 'medium',
  },
]

export const CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    name: 'Spring Office Revival — Unique',
    brand: 'unique',
    type: 'recruitment',
    status: 'approved',
    startDate: '2026-05-05',
    endDate: '2026-06-15',
    budget: 45000,
    spent: 0,
    healthScore: 82,
    channels: ['linkedin', 'instagram', 'email', 'website'],
    owner: 'Sophie Martens',
    objective: 'Drive 200 qualified office profile applications in Q2',
    readiness: 91,
    approvalStatus: 'approved',
    kpis: [
      { label: 'Applications', target: '200', actual: '0', achieved: false },
      { label: 'CTR', target: '2.5%', actual: '0%', achieved: false },
      { label: 'Cost per Apply', target: '€85', actual: '—', achieved: false },
    ],
  },
  {
    id: 'c2',
    name: 'Flex Work Month — Start People',
    brand: 'start-people',
    type: 'awareness',
    status: 'live',
    startDate: '2026-04-01',
    endDate: '2026-04-30',
    budget: 32000,
    spent: 28400,
    healthScore: 74,
    channels: ['facebook', 'instagram', 'display', 'email'],
    owner: 'Thomas Dubois',
    objective: 'Increase flex worker registrations by 25% in April',
    readiness: 100,
    approvalStatus: 'approved',
    kpis: [
      { label: 'Registrations', target: '500', actual: '412', achieved: false },
      { label: 'CTR', target: '3.0%', actual: '2.7%', achieved: false },
      { label: 'Cost per Registration', target: '€64', actual: '€69', achieved: false },
    ],
  },
  {
    id: 'c3',
    name: 'Healthcare Heroes — Express Medical',
    brand: 'express-medical',
    type: 'recruitment',
    status: 'live',
    startDate: '2026-03-15',
    endDate: '2026-05-31',
    budget: 28000,
    spent: 14200,
    healthScore: 61,
    channels: ['linkedin', 'facebook', 'email', 'search'],
    owner: 'Digital Team',
    objective: 'Source 150 healthcare professionals for Q2 pipeline',
    readiness: 100,
    approvalStatus: 'approved',
    kpis: [
      { label: 'Profiles Sourced', target: '150', actual: '72', achieved: false },
      { label: 'Email Open Rate', target: '28%', actual: '31%', achieved: true },
      { label: 'LinkedIn CTR', target: '1.8%', actual: '1.2%', achieved: false },
    ],
  },
  {
    id: 'c4',
    name: 'Executive Search 2026 — Bright Plus',
    brand: 'bright-plus',
    type: 'employer-branding',
    status: 'planning',
    startDate: '2026-06-01',
    endDate: '2026-08-31',
    budget: 55000,
    spent: 0,
    healthScore: 45,
    channels: ['linkedin', 'email', 'website', 'print'],
    owner: 'Brand Marketing',
    objective: 'Position Bright Plus as #1 executive search brand in Belgium',
    readiness: 38,
    approvalStatus: 'pending',
    kpis: [
      { label: 'Brand Awareness', target: '+15%', actual: '—', achieved: false },
      { label: 'Senior Leads', target: '80', actual: '—', achieved: false },
    ],
  },
  {
    id: 'c5',
    name: 'IT Talent Pipeline — USG Professionals',
    brand: 'usg-professionals',
    type: 'recruitment',
    status: 'planning',
    startDate: '2026-05-20',
    endDate: '2026-07-31',
    budget: 38000,
    spent: 0,
    healthScore: 55,
    channels: ['linkedin', 'youtube', 'email', 'website'],
    owner: 'Digital Team',
    objective: 'Build IT candidate pipeline with 300 qualified profiles',
    readiness: 62,
    approvalStatus: 'pending',
    kpis: [
      { label: 'IT Profiles', target: '300', actual: '—', achieved: false },
      { label: 'Video Views', target: '50K', actual: '—', achieved: false },
    ],
  },
  {
    id: 'c6',
    name: 'HR Solutions Spring — Solvus',
    brand: 'solvus',
    type: 'lead-gen',
    status: 'live',
    startDate: '2026-04-10',
    endDate: '2026-05-31',
    budget: 22000,
    spent: 9800,
    healthScore: 88,
    channels: ['linkedin', 'email', 'website'],
    owner: 'Solvus Marketing',
    objective: 'Generate 40 qualified HR outsourcing leads for Sales',
    readiness: 100,
    approvalStatus: 'approved',
    kpis: [
      { label: 'MQLs', target: '40', actual: '29', achieved: false },
      { label: 'LinkedIn CTR', target: '2.2%', actual: '2.8%', achieved: true },
      { label: 'Cost per MQL', target: '€550', actual: '€338', achieved: true },
    ],
  },
]

export const STRATEGY_PILLARS: StrategyPillar[] = [
  {
    id: 'sp1',
    title: 'Employer Brand Strengthening',
    description: 'Elevate RGF Belgium brands as preferred employers across all markets and candidate segments.',
    priority: 1,
    brand: 'group',
    budget: 180000,
    budgetUsed: 62000,
    campaigns: 4,
    status: 'on-track',
  },
  {
    id: 'sp2',
    title: 'Digital-First Candidate Acquisition',
    description: 'Shift 70% of candidate sourcing to digital channels by end of 2026.',
    priority: 2,
    brand: 'group',
    budget: 240000,
    budgetUsed: 98000,
    campaigns: 7,
    status: 'at-risk',
  },
  {
    id: 'sp3',
    title: 'Sales Enablement & B2B Lead Generation',
    description: 'Provide Sales with world-class marketing tools, content and qualified leads.',
    priority: 3,
    brand: 'group',
    budget: 120000,
    budgetUsed: 41000,
    campaigns: 3,
    status: 'on-track',
  },
  {
    id: 'sp4',
    title: 'Brand Consistency & Compliance',
    description: 'Ensure 100% brand guideline compliance across all digital and offline touchpoints.',
    priority: 4,
    brand: 'group',
    budget: 60000,
    budgetUsed: 18000,
    campaigns: 0,
    status: 'behind',
  },
]

export const BUDGET_BY_BRAND: BudgetAllocation[] = [
  { brand: 'start-people', total: 180000, allocated: 165000, spent: 82400, remaining: 97600 },
  { brand: 'unique', total: 140000, allocated: 130000, spent: 54200, remaining: 85800 },
  { brand: 'express-medical', total: 90000, allocated: 82000, spent: 38600, remaining: 51400 },
  { brand: 'solvus', total: 75000, allocated: 70000, spent: 28900, remaining: 46100 },
  { brand: 'bright-plus', total: 110000, allocated: 95000, spent: 31200, remaining: 78800 },
  { brand: 'usg-professionals', total: 95000, allocated: 85000, spent: 22100, remaining: 72900 },
]

export const CONTENT_ASSETS: ContentAsset[] = [
  {
    id: 'ca1',
    title: 'Unique Spring — LinkedIn Ad Set (3 variants)',
    type: 'visual',
    brand: 'unique',
    campaign: 'Spring Office Revival',
    channel: 'linkedin',
    status: 'approved',
    createdAt: '2026-04-20',
    owner: 'Sophie Martens',
    tags: ['spring', 'office', 'recruitment', 'linkedin'],
  },
  {
    id: 'ca2',
    title: 'Start People Flex Reel — "Your Way to Work"',
    type: 'video',
    brand: 'start-people',
    campaign: 'Flex Work Month',
    channel: 'instagram',
    status: 'published',
    createdAt: '2026-04-01',
    owner: 'Content Team',
    tags: ['video', 'flex', 'instagram', 'reel'],
  },
  {
    id: 'ca3',
    title: 'Express Medical — Candidate Email Sequence (5 emails)',
    type: 'copy',
    brand: 'express-medical',
    campaign: 'Healthcare Heroes',
    channel: 'email',
    status: 'approved',
    createdAt: '2026-03-10',
    owner: 'Thomas Dubois',
    tags: ['email', 'healthcare', 'candidate'],
  },
  {
    id: 'ca4',
    title: 'Bright Plus Brand Manifesto Video',
    type: 'video',
    brand: 'bright-plus',
    status: 'review',
    createdAt: '2026-04-25',
    owner: 'Brand Team',
    tags: ['video', 'brand', 'executive'],
  },
  {
    id: 'ca5',
    title: 'USG Professionals — IT Campaign Brief Template',
    type: 'template',
    brand: 'usg-professionals',
    status: 'draft',
    createdAt: '2026-04-28',
    owner: 'Digital Team',
    tags: ['template', 'IT', 'brief'],
  },
  {
    id: 'ca6',
    title: 'Solvus HR Solutions — Landing Page Copy',
    type: 'copy',
    brand: 'solvus',
    campaign: 'HR Solutions Spring',
    channel: 'website',
    status: 'published',
    createdAt: '2026-04-09',
    owner: 'Solvus Marketing',
    tags: ['landing-page', 'B2B', 'hr'],
  },
]

export const SALES_ASSETS: SalesAsset[] = [
  {
    id: 'sa1',
    title: 'Unique — Office Staffing Pitch Deck 2026',
    type: 'pitch-deck',
    brand: 'unique',
    segment: 'SME',
    language: 'fr',
    status: 'approved',
    downloads: 47,
    updatedAt: '2026-04-15',
  },
  {
    id: 'sa2',
    title: 'Start People — Flex Workforce One-Pager',
    type: 'one-pager',
    brand: 'start-people',
    segment: 'Enterprise',
    language: 'nl',
    status: 'approved',
    downloads: 83,
    updatedAt: '2026-04-02',
  },
  {
    id: 'sa3',
    title: 'Bright Plus — Executive Search Case Study: ENGIE',
    type: 'case-study',
    brand: 'bright-plus',
    segment: 'Enterprise',
    language: 'en',
    status: 'approved',
    downloads: 31,
    updatedAt: '2026-03-28',
  },
  {
    id: 'sa4',
    title: 'Solvus — HR Outsourcing Battle Card',
    type: 'battle-card',
    brand: 'solvus',
    segment: 'Mid-Market',
    language: 'fr',
    status: 'review',
    downloads: 12,
    updatedAt: '2026-04-22',
  },
  {
    id: 'sa5',
    title: 'USG Professionals — IT Profiles Brochure',
    type: 'brochure',
    brand: 'usg-professionals',
    segment: 'Tech',
    language: 'en',
    status: 'approved',
    downloads: 28,
    updatedAt: '2026-04-10',
  },
  {
    id: 'sa6',
    title: 'Express Medical — Healthcare Staffing Pitch',
    type: 'pitch-deck',
    brand: 'express-medical',
    segment: 'Hospital & Clinic',
    language: 'fr',
    status: 'approved',
    downloads: 19,
    updatedAt: '2026-03-20',
  },
]

export const PERFORMANCE_METRICS: PerformanceMetric[] = [
  { channel: 'linkedin', impressions: 284000, clicks: 6820, conversions: 312, ctr: 2.4, cpc: 4.8, spend: 32800, roi: 3.2 },
  { channel: 'instagram', impressions: 198000, clicks: 5240, conversions: 198, ctr: 2.6, cpc: 3.2, spend: 16800, roi: 2.8 },
  { channel: 'facebook', impressions: 312000, clicks: 7180, conversions: 280, ctr: 2.3, cpc: 2.9, spend: 20800, roi: 2.4 },
  { channel: 'email', impressions: 48000, clicks: 9840, conversions: 580, ctr: 20.5, cpc: 0.8, spend: 7900, roi: 5.8 },
  { channel: 'youtube', impressions: 142000, clicks: 2840, conversions: 89, ctr: 2.0, cpc: 5.6, spend: 15900, roi: 1.9 },
  { channel: 'website', impressions: 95000, clicks: 18200, conversions: 820, ctr: 19.2, cpc: 0, spend: 0, roi: 0 },
  { channel: 'search', impressions: 68000, clicks: 3400, conversions: 210, ctr: 5.0, cpc: 6.2, spend: 21100, roi: 3.6 },
]

export const APPROVAL_REQUESTS: ApprovalRequest[] = [
  {
    id: 'ar1',
    title: 'Bright Plus Executive Search Campaign 2026',
    type: 'campaign',
    brand: 'bright-plus',
    submittedBy: 'Brand Marketing',
    submittedAt: '2026-04-28',
    deadline: '2026-05-03',
    status: 'pending',
    reviewers: ['Christophe Halart', 'Legal & Compliance'],
    priority: 'urgent',
  },
  {
    id: 'ar2',
    title: 'USG Professionals IT Campaign Brief',
    type: 'campaign',
    brand: 'usg-professionals',
    submittedBy: 'Digital Team',
    submittedAt: '2026-04-29',
    deadline: '2026-05-06',
    status: 'pending',
    reviewers: ['Christophe Halart'],
    priority: 'normal',
  },
  {
    id: 'ar3',
    title: 'Solvus Q2 Budget Increase (+€15K)',
    type: 'budget',
    brand: 'solvus',
    submittedBy: 'Solvus Marketing',
    submittedAt: '2026-04-27',
    deadline: '2026-05-05',
    status: 'pending',
    reviewers: ['Christophe Halart', 'Finance'],
    priority: 'normal',
  },
  {
    id: 'ar4',
    title: 'Start People Brand Guidelines v3.2',
    type: 'strategy',
    brand: 'start-people',
    submittedBy: 'Thomas Dubois',
    submittedAt: '2026-04-25',
    deadline: '2026-05-10',
    status: 'changes-requested',
    reviewers: ['Christophe Halart'],
    priority: 'low',
  },
]

export const COMPLIANCE_ITEMS: ComplianceItem[] = [
  { id: 'ci1', title: 'Email consent database audit', brand: 'group', category: 'gdpr', status: 'review-needed', lastChecked: '2026-03-15', owner: 'Legal & Compliance' },
  { id: 'ci2', title: 'Solvus logo usage on partner sites', brand: 'solvus', category: 'brand-guidelines', status: 'non-compliant', lastChecked: '2026-04-20', owner: 'Brand Team' },
  { id: 'ci3', title: 'GDPR cookie banner — all brand sites', brand: 'group', category: 'gdpr', status: 'compliant', lastChecked: '2026-04-28', owner: 'Digital Team' },
  { id: 'ci4', title: 'Candidate data retention policy', brand: 'group', category: 'gdpr', status: 'compliant', lastChecked: '2026-04-15', owner: 'Legal & Compliance' },
  { id: 'ci5', title: 'Express Medical healthcare advertising claims', brand: 'express-medical', category: 'legal', status: 'review-needed', lastChecked: '2026-04-10', owner: 'Legal & Compliance' },
]

export const COMMAND_CENTER_KPIS: KPI[] = [
  { label: 'Active Campaigns', value: '12', change: 2, trend: 'up', period: 'vs last month' },
  { label: 'Campaign Readiness', value: '74%', change: -6, trend: 'down', period: 'vs last month' },
  { label: 'Budget Utilization', value: '38%', change: 4, trend: 'up', period: 'YTD vs plan' },
  { label: 'Content Published', value: '48', change: 12, trend: 'up', period: 'this month' },
  { label: 'Approvals Pending', value: '4', change: 2, trend: 'down', period: 'open items' },
  { label: 'Avg. Campaign Health', value: '68/100', change: -3, trend: 'down', period: 'vs last month' },
]

export const MONTHLY_PERFORMANCE_DATA = [
  { month: 'Jan', spend: 38000, leads: 180, applications: 320 },
  { month: 'Feb', spend: 42000, leads: 210, applications: 380 },
  { month: 'Mar', spend: 55000, leads: 290, applications: 480 },
  { month: 'Apr', spend: 61000, leads: 320, applications: 540 },
  { month: 'May', spend: 48000, leads: 0, applications: 0 },
]

export const CHANNEL_MIX_DATA = [
  { name: 'LinkedIn', value: 32, color: '#0077B5' },
  { name: 'Email', value: 18, color: '#7c3aed' },
  { name: 'Facebook', value: 16, color: '#1877F2' },
  { name: 'Instagram', value: 14, color: '#E4405F' },
  { name: 'Search', value: 12, color: '#34A853' },
  { name: 'YouTube', value: 8, color: '#FF0000' },
]
